apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app
  labels:
    app: simple-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-flask-app
  template:
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
      - name: simple-flask-app
        image: deeptidevadiga/cafestatic:v3 # deeptidevadiga/simple-flask:v1 
        ports:
        - containerPort: 5070   # Flask runs on port 5070

